### PR TITLE
Extend airbnb, prettier and flow 

### PR DESCRIPTION
**Pull request by charliesbox**
- Added airbnb eslint plugin
- Added prettier eslint plugin
- Added flowtype eslint plugin with coverage

### CODE REVIEW

**Comment by CesarLanderos** [comment]
😱

**Comment by charliesbox** [comment]
@bit-dragon nope, they will continue using v1.1. New repos like phoenix will use this version that depends on airbnb (huge change) and prettier plugin

**Comment by CesarLanderos** [comment]
@bit-dragon yeah, this Pr should bump the version to 2.0.0, and, right now, it seems to be only the linting part, right @charliesbox ?

**Comment by charliesbox** [comment]
@CesarLanderos tricky question. Yes, it is for linting, but having the plugin means that we're gonna enforce prettier, airbnb rules and flow.

Not a biggie, cause most of the rules from prettier are already part of airbnb, but with the fix solution.

Also, next PR will bump the version, as we are doing so far.

**Pull request merged**
